removes dependencys from other repos, removes bad features, makes it work, update to 144.2
Apricot-Conservation-Project/Plague-Plugin pull request #1
Opened 2023-05-22 11:12 UTC by bend-n

2023-05-22 23:16 UTC, bend-n commented
@nilederg can we try it?

2023-05-23 03:42 UTC, nilederg commented
hmmm

2023-05-23 04:21 UTC, nilederg commented on plugin.json
better to credit to "ACP Developers"

2023-05-23 04:31 UTC, nilederg requested changes
Please change credit to the more general "ACP Developers". Fixing the rest of the formatting can happen in a different PR. Thanks for the work removing the excess code and bloat. That plus the reformatting makes it look a lot nicer.

2023-05-23 04:32 UTC, nilederg approved these changes
Thanks for removing the bloat. LGTM.

2023-05-23 04:33 UTC, nilederg commented
I'll leave the merge to you.

2023-05-23 04:39 UTC, closed without merging